[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quantum_error_lib"
version = "0.1.0"
description = "A library for verifying quantum error code decoders"
authors = [{ name = "Ryan Kersten", email = "ryankers@umich.edu" }]
dependencies = []